name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Executa o pipeline quando houver um push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t your-app-name:latest .

      # Fazer login no Docker Hub (ou outro container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:D
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push da imagem Docker para o Docker Hub
      - name: Push Docker image
        run: |
          docker tag your-app-name:latest your-docker-username/your-app-name:latest
          docker push your-docker-username/your-app-name:latest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login no Docker Hub (ou registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Deployment para o ambiente de staging usando Docker Compose
      - name: Deploy to Staging
        run: |
          docker-compose -f docker-compose.yml up -d
