name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file EcoClean/EcoClean/Dockerfile --tag eco-clean:latest

      - name: Run Tests
        run: |
          cd EcoCleanTest
          dotnet test

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Staging
        run: |
          docker stop eco-clean-staging || true
          docker rm eco-clean-staging || true
          docker run -d --name eco-clean-staging -p 8081:8080 eco-clean:latest

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Deploy to Production
        run: |
          docker stop eco-clean-production || true
          docker rm eco-clean-production || true
          docker run -d --name eco-clean-production -p 80:8080 eco-clean:latest
